spring:
  datasource:
    url: jdbc:h2:mem:character
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect